# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "Championship", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
    t.column "begin", :date, :null => false
    t.column "end", :date, :null => false
    t.column "point_win", :integer, :limit => 4, :default => 3, :null => false
    t.column "point_draw", :integer, :limit => 4, :default => 1, :null => false
    t.column "point_loss", :integer, :limit => 4, :default => 0, :null => false
  end

  create_table "Game", :force => true do |t|
    t.column "home", :integer, :limit => 20, :default => 0, :null => false
    t.column "away", :integer, :limit => 20, :default => 0, :null => false
    t.column "phase", :integer, :limit => 20
    t.column "round", :integer, :limit => 4
    t.column "attendance", :integer, :limit => 9
    t.column "date", :datetime, :null => false
    t.column "stadium", :integer, :limit => 20
    t.column "referee", :integer, :limit => 20
    t.column "home_score", :integer, :limit => 2, :default => 0, :null => false
    t.column "away_score", :integer, :limit => 2, :default => 0, :null => false
    t.column "home_pen", :integer, :limit => 2
    t.column "away_pen", :integer, :limit => 2
    t.column "played", :string, :limit => 0, :default => "scheduled", :null => false
  end

  create_table "Goal", :force => true do |t|
    t.column "player", :integer, :limit => 20, :default => 0, :null => false
    t.column "game", :integer, :limit => 20, :default => 0, :null => false
    t.column "team", :integer, :limit => 20, :default => 0, :null => false
    t.column "time", :integer, :limit => 4, :default => 0, :null => false
    t.column "penalty", :string, :limit => 0, :default => "0", :null => false
    t.column "own_goal", :string, :limit => 0, :default => "0", :null => false
  end

  add_index "Goal", ["player", "game"], :name => "player"

